FROM ghcr.io/mehal-tech/amrite:main as crunbuild 
FROM ghcr.io/mehal-tech/brog:main as brogbuild 

FROM quay.io/fedora/fedora-bootc:41

RUN dnf -y install mkpasswd
RUN pass=$(mkpasswd --method=SHA-512 --rounds=4096 thepassword) && useradd -m -G wheel bootcer -p $pass
RUN echo "%wheel        ALL=(ALL)       NOPASSWD: ALL" > /etc/sudoers.d/wheel-sudo

######################################################
# amrite install for wasi support
######################################################
COPY --from=crunbuild /vendor/fedora_41/libwasmedge.so.0 /usr/local/lib64/libwasmedge.so.0 
COPY --from=crunbuild /vendor/fedora_41/crun-wasmedge /usr/bin/crun

######################################################
# brog install for OS updates
######################################################
# Disable auto updates as we are going to use brog
RUN systemctl disable bootc-fetch-apply-updates.timer
COPY --from=brogbuild  /brog /usr/bin
RUN systemctl disable bootc-fetch-apply-updates.timer
COPY --from=brogbuild /vendor/fedora_41/brog /usr/bin/brog

COPY <<"EOT" /usr/lib/systemd/system/brog.service
[Unit]
Description=A bootc management service
After=network.target

[Service]
Type=simple
RemainAfterExit=yes
ExecStart=/usr/bin/brog
TimeoutStartSec=0
Environment=ENDPOINT=https://global.mehal.tech/gitops/project/config
Environment=SCHEDULE="every 120 seconds"

[Install]
WantedBy=default.target
EOT

# Enable the service
# We prefer using systemctl over a manual symlink 
RUN systemctl enable brog.service