FROM ghcr.io/ubiquitous-factory/amrite:main as crunbuild 
FROM ghcr.io/ubiquitous-factory/brog:main as brogbuild 

FROM quay.io/fedora/fedora-bootc:41

RUN dnf -y install mkpasswd
RUN pass=$(mkpasswd --method=SHA-512 --rounds=4096 thepassword) && useradd -m -G wheel bootcer -p $pass
RUN echo "%wheel        ALL=(ALL)       NOPASSWD: ALL" > /etc/sudoers.d/wheel-sudo

######################################################
# amrite install for wasi support
######################################################
COPY --from=crunbuild /vendor/fedora_41/libwasmedge.so.0 /usr/local/lib64/libwasmedge.so.0 
COPY --from=crunbuild /vendor/fedora_41/crun-wasmedge /usr/bin/crun

######################################################
# brog install for OS updates
######################################################
# Disable auto updates as we are going to use brog
RUN systemctl disable bootc-fetch-apply-updates.timer
COPY --from=brogbuild  /vendor/fedora_41/brog /usr/bin
COPY brog.service /etc/systemd/system

# Enable the service
RUN mkdir -p /etc/systemd/system/default.target.wants
RUN ln -s /etc/systemd/system/brog.service /etc/systemd/system/default.target.wants/brog.service
