FROM ghcr.io/ubiquitous-factory/amrite:main as crunbuild 
FROM ghcr.io/ubiquitous-factory/brog:main as brogbuild 

FROM quay.io/fedora/fedora-bootc:41

# bootupd currently does not support Raspberry Pi-specific firmware and bootloader files.
# This shim script copies the firmware and bootloader files to the correct location before
# calling the original bootupctl script.
# This is a temporary workaround until https://github.com/coreos/bootupd/issues/651 is resolved.
RUN dnf install -y bcm283x-firmware bcm283x-overlays uboot-images-armv8 && \
    cp -P /usr/share/uboot/rpi_arm64/u-boot.bin /boot/efi/rpi-u-boot.bin && \
    mkdir -p /usr/lib/bootc-raspi-firmwares && \
    cp -a /boot/efi/. /usr/lib/bootc-raspi-firmwares/ && \
    dnf remove -y bcm283x-firmware uboot-images-armv8 && \
    mkdir /usr/bin/bootupctl-orig && \
    mv /usr/bin/bootupctl /usr/bin/bootupctl-orig/ && \
    dnf clean all


COPY bootupctl-shim /usr/bin/bootupctl

######################################################
# amrite install for wasi support
######################################################
COPY --from=crunbuild /vendor/fedora_41/libwasmedge.so.0 /usr/local/lib64/libwasmedge.so.0 
COPY --from=crunbuild /vendor/fedora_41/crun-wasmedge /usr/bin/crun

######################################################
# brog install for OS updates
######################################################
# Disable auto updates as we are going to use brog
RUN systemctl disable bootc-fetch-apply-updates.timer
COPY --from=brogbuild  /vendor/fedora_41/brog /usr/bin
COPY brog.service /etc/systemd/system

# Enable the service
RUN mkdir -p /etc/systemd/system/default.target.wants
RUN ln -s /etc/systemd/system/brog.service /etc/systemd/system/default.target.wants/brog.service